# Generated by Django 4.2.1 on 2023-07-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_Firstname', models.CharField(max_length=200)),
                ('emp_Lastname', models.CharField(max_length=500)),
                ('emp_Dob', models.DateField()),
                ('emp_Gender', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_username', models.CharField(max_length=50)),
                ('us_password', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(default=0)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRManagement.employee')),
            ],
        ),
    ]
